config/routes.rb
Kuret::Application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'
  devise_for :admins
  resources :blogs
  resources :skills
  resources :works
  resources :bios
  resources :contacts, only: [:new, :create]

  get 'sign_in', to: 'devise/session#new', as:"signin"
  get 'sign_out', to: 'devise/session#destroy', as: "signout"
  get "bios/content"
  get "works/index"
  get "skills/index"
  get "main/index"
  get 'contact', to: 'contacts#new', via: :get
  get 'contact', to: 'contacts#create', via: :post

  root 'main#index', as: "home"

  

end

app/controllers/main_controller.rb
class MainController < ApplicationController

  def index
  	starting_year = 1998
  	@years_of_experience = (Time.now.strftime("%Y").to_i) - starting_year
  	@bios= Bio.all
  	@contact = Contact.new
  	@works = Work.all.order("created_at DESC")
  	@skills = Skill.all
        @blogs = Blog.all.order("created_at DESC").limit(2)
  	@client = Twitter::REST::Client.new do |config|
	  config.consumer_key        = "rjff2Gue1qFv1nUsamy7Jg"
	  config.consumer_secret     = "hW3vbTEd0c5WypFb4dFHtucpTzgazqBTT1Dktr3fY7s"
	  config.access_token        = "84047853-Piq1HiaoRK3o10griTK7orBspxnxayK5g5X5Qhj5H"
	  config.access_token_secret = "mAb0kyCIIQw9FMXjUxPuSy0NQGMOLV3iLjwFARCmNfAUp"
	end
  end

end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/_about.html.erb
<div class="row">
	<!-- About me -->
	<h2 data-megallen-destination="about" ></h2>
	<div class="large-4 medium-4 columns c1">
		<div class="row">
			<div class="large-6 small-6 medium-6 columns">
				<div class="circle_pic">
					<div class="circle">
						<%= image_tag 'me.jpg', class: "my_pic" %>
					</div>
				</div>
			</div>
			<div class="large-6 small-6 medium-6 columns">
				<div class="large-6 small-6">
					<h2 class="about"><strong>ABOUT</strong> <span>ME</span></h2>
				</div>
			</div>
			<hr />
			<div class="large-4 ">
				<h2 class="subheader"><strong>BIO:</strong></h2>
			</div>
			<div class="large-12">
				<% @bios.each do |bio| %>
					<p class="white"><%= bio.content %></p>
				<% end %>
			</div>
		</div>
	</div>
	<!-- Current Location -->
	<div class="large-4 medium-4 columns c2">
		<div class="large-12"><h2 class="subheader"><strong>CURRENT LOCATION:</strong></h2></div>
		<div class="large-12"><p>SLOVENIJA</p></div>
		<div id="map" class="large-12">
			<%= image_tag 'slo.png', class: 'slo_pic' %>
		</div>
		<hr />
	</div>
	<div class="large-4 medium-4 columns c3">
		<!-- I'm all about -->
		<div class="large-12 small-12 medium-12 c32"><h2 class="subheader"><strong>I'M ALL ABOUT:</strong></h2></div>
		<div class="large-12 medium-12 small-12 why c32">
			<ul>
				<li>making client happy</li>
				<li>simplicity</li>
				<li>easy to use</li>
				<li>unique</li>
			</ul>
		</div>
		<!-- My carere -->
		<div class="large-12 c3carere"><h2 class="subheader"><strong>MY CARERE:</strong></h2></div>
			<div class="row carere">
				<div class="large-5 small-5 columns year c33"><%= @years_of_experience %></div>
				<div class="large-7 small-7 small-push-1 columns xp c33">
					<p>YEARS</p>
					<p>OF</p>
					<p>EXPERIENCES</p>
				</div>
			</div>
				<div class="large-2 small-3 medium-2 columns c33"><h3 class="subheader"><strong>In: </strong></h3></div>
				<div class="large-10 small-9 medium-10 columns c33">
					<ul>
						<li>COMPUTER REPAIR</li>
						<li>NETWORK CONFIG</li>
						<li>WEB DEVELEPMENT</li>
						<li>OSC & ANDROID ROOT</li>
						<li>MOBILE REPAIR</li>
					</ul>
				</div>
	</div>
	<div class="large-12">
		<a name="skills"></a>
		<h2 data-magellan-destination="skills" ></h2>
		<%= render 'skils' %>
	</div>
</div>

app/views/main/_blog.html.erb
<div class="large-5 medium-5 small-11 push-1 columns blog">
<div class="large-12"><h5><strong>What's on my mind</strong></h5></div>
                        <% @blogs.each do |blog| %>
                                <div class="large-11 small-11 medium-11">
                                        <div class="large-10 small-10 medium-10 columns"><span><%= blog.title %></span></div>
                                </div>
                                <div class="large-11 small-11 medium-11">
                                        <div class="large-2 small-2 medium-11 columns"></div>
                                        <div class="large-10 small-10 medium-11 columns description"><%= truncate(blog.description, length: 100) %><%= link_to "Read more", blog  %><hr /></div>
                                </div>
                        <% end %>
                        <div class="large-12 columns more">
                                <%= link_to "All Blogs", blogs_path %>
                        </div>
</div>

app/views/main/_contact.html.erb
<div class="large-12 contact_top_padding"></div>
<div class="row">
	<div class="large-6 small-10 columns contact_new">
		<%= render 'contacts/new' %>
	</div>
	<div class="large-4 small-10 columns large-push-1">
		<div class="large-11 small-11" style="background-color:#212326;padding:20px 0 20px 20px;">
			<h5 style="color:white"><strong>Contact details</strong></h5>
			<p style="color:gray">Andraz Kuret<br />
				<span style="color:red">info@kuret.me</span><br />
				(+386)40 134 277</p>
			<p style="color:gray">Titov trg 3<br />
				6230 Postojna<br />
				Slovenia</p>
		</div>
	</div>
	<div id="ajax_call" class="large-12">
		<div id="circular3dG">
			<div id="circular3d_1G" class="circular3dG"></div>
			<div id="circular3d_2G" class="circular3dG"></div>
			<div id="circular3d_3G" class="circular3dG"></div>
			<div id="circular3d_4G" class="circular3dG"></div>
			<div id="circular3d_5G" class="circular3dG"></div>
			<div id="circular3d_6G" class="circular3dG"></div>
			<div id="circular3d_7G" class="circular3dG"></div>
			<div id="circular3d_8G" class="circular3dG"></div>
		</div> 
	</div>
</div>

app/views/main/_skils.html.erb
<div class="row">
	<div id="diagram" class="large-12 small-12 columns"></div>
	<div id="skilcirle" class="large-12 small-12 columns"></div>
	<% @skills.each do |skill| %>
	<div class="skills_adj large-1 small-1 columns">
		<span class="text"><%= skill.name %></span>
		<input type="hidden" class="percent" value="<%= skill.procents %>">
	</div>
	<% end %>
</div>

app/views/main/_social.html.erb
<div class="row">
	<div class="large-5 medium-5 small-12 columns tweets">
		<div class="large-12">
			<h4>Tweets table: </h4>
		</div>
				<% @client.user_timeline(count:2).each do |tweet| %>
			<div class="large-12">
				<%= image_tag(tweet.user.profile_image_url) %>
				<p><%= tweet.text %></p><br />
			</div>
		<% end %>

	</div>
	<div class="large-6 medium-6 columns small-12 ">
		<h2 data-magellan-destination="social" ></h2>
		<div id="social_fb" class="large-3 small-3 medium-3 columns"></div>
		<div id="social_tw" class="large-3 small-3 medium-3 columns"></div>
		<div id="social_git" class="large-3 small-3 medium-3 columns"></div>
		<div id="social_sk" class="large-3 small-3 medium-3 columns"></div>
	</div>
</div>

app/views/main/_work.html.erb
	<h2 data-magellan-destination="work" ></h2>
		<div class="large-6 small-11 medium-7 work columns">
			<% @works.each do |work| %>
				<a href="http://www.<%= work.link %>" target="_blank" >
					<div class="large-12 work1">
						<div class="work_image large-7 small-7 medium-7 columns">
							<%= image_tag(work.image.url(:thumb)) %>
						</div>
						<div class="p large-5 small-5 medium-5 columns">
							<p><span><b>Project:</b></span> <br /><span><%= work.project %></span></p>
							<p><span><b>Desciption:</b></span><br /><span><%= work.description %></span></p>
						</div>
					</div>
				</a>
			<% end %>
		</div>

app/views/main/index.html.erb
<% meta :description => "Ruby on Rails, Jquery,  Web Developer, computer IT specialist, computers services. Strategy great, fast and powerfull projects, systems and applications. Andraz Kuret" %>
<div data-magellan-destination="home" id="main" class="front">
    <a name="home"></a>
     	<div id="matx"> 
         <div class="t1" style="left:2px;">I like to code and code and code</div>
         <div class="t5" style="left:45px;">Ruby on rails Javascript Jquery Mysql</div>
         <div class="t1" style="left:180px;">createve web development</div>
         <div class="t2" style="left:300px;">I like to code and code and code</div>
         <div class="t4" style="left:330px;">Ruby on rails Javascript Jquery Mysql</div>
         <div class="t2" style="left:360px;">how to create</div>
         <div class="t3" style="left:390px;">Ruby on rails Javascript Jquery Mysql</div>
         <div class="t1" style="left:405px;">createve web development</div>
         <div class="t3" style="left:420px;">I like to code and code and code</div>
         <div class="t5" style="left:470px;">Ruby on rails Javascript Jquery Mysql</div>
         <div class="t2" style="left:410px;">I like to code and code and code</div>
         <div class="t3" style="left:530px;">Ruby on rails Javascript Jquery Mysql</div>
         <div class="t5" style="left:570px;">Create Slide Show With Pure CSS3</div>
         <div class="t4" style="left:610px;">I like to code and code and code</div>
         <div class="t2" style="left:650px;">Ruby on rails Javascript Jquery Mysql</div>
         <div class="t1" style="left:690px;">createve web development</div>
         <div class="t3" style="left:810px;">I like to code and code and code</div>
         <div class="t5" style="left:840px;">Ruby on rails Javascript Jquery Mysql</div>
         <div class="t2" style="left:870px;">I like to code and code and code</div>
    </div> 
                <div id="quote" class="row">
                    <div class="large-12 medium-12 small-12">
                        <h1 class="animated bounceIn" style="color:white"><strong>Technology addicted <span class="highlight lime">Javascript, </span> <span class="highlight light">and </span> Ruby on Rails <span class="highlight light">developer</span> who like to think differente</strong></h1>
                    </div>
                    <div class="large-12 medium-12 small-12 nav">
                        <ul>
                            <li class="button"><a href="#home">Home</a></li>
                            <li class="button"><a href="#work">Work</a></li>
                            <li class="button"><a href="#about">About</a></li>
                            <li class="button"><a href="#skills">Skills</a></li>
                            <li class="button"><a href="#contact">Contact</a></li>
                            <li class="button"><a href="#social">Social</a></li>
                        </ul>
                    </div>
                </div> 

</div>

<div id="work" class="large-12">
    <a name="work"></a>
    <div class="row">
	<%= render 'work' %>
	<%= render 'blog' %>
    </div>
</div>

<div id="about" class="large-12">
    <a name="about"></a>
	<%= render 'about' %>
</div>

<div id="contact" class="large-12">
    <a name="contact"></a>
	<%= render 'contact' %>
</div>

<div id="social" class="large-12">
    <a name="social"></a>
	<%= render 'social' %>
</div>
<div class="footer large-12">
	<div class="large-12 footer_btw"></div>
	<div class="large-8 medium-8 small-12 columns cp">Copyright © 2014 | All Rights Reserved by the site owner</div>
	<div class="large-2 medium-2 small-12 columns">
		<a href="https://plus.google.com/+andrazkuret?rel=author" rel="publisher" target="_blank" title="Google+">Google+</a>
	</div>
	<div class="large-2 medium-2 small-12 columns">
		<ul>
 			<% if current_admin %>
				<li><%= link_to 'Sign out', destroy_admin_session_path, method: :delete %></li>	
			<% else %>
				<li><%= link_to 'Sign in', new_admin_session_path %></li>
  			<% end %>
		</ul>
	</div>
</div>